apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openlake.fullname" . }}-credentials
  labels:
    {{- include "openlake.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.credentials.accessKey | quote }}
  secretKey: {{ .Values.credentials.secretKey | quote }}
