self_id = 1
rpc_addr = "127.0.0.1:7001"
s3_addr = "127.0.0.1:9000"
s3_port = 9000
data_dirs = ["./data1", "./data2"]
set_drive_count = 2
default_parity_count = 1
region = "us-east-1"

[[credentials]]
access_key = "admin"
secret_key = "admin"

[[nodes]]
id = 1
rpc_addr = "127.0.0.1:7001"
disk_count = 2