apiVersion: v2
name: openlake
type: application
version: 0.1.0
appVersion: "0.1.0"
description: openlake high performance object storage for GPU workloads
kubeVersion: ">=1.28.0-0"
icon: https://openlake.dev/favicon.png
sources:
  - https://github.com/openlake-project/openlake
